---
- name: create an f5 cluster in azure
  hosts: localhost

  tasks:
    # Destroy a template deployment
    - name: Destroy Azure Deploy
      azure_rm_deployment:
        state: absent
        resource_group_name: f5demo-rg
