---
#VARs for new 3nic cluster

#Azure
resourceGroup: 
dnsLabel: 
location:

#F5 Intance
adminUsername:  
adminPassword: 
#dnsLabel:
#instanceName:
instanceType: Standard_DS4_v2
imageName: Best
#bigIpVersion: 13.0.0300 | 12.1.2200 | latest

#BYOL
licenseKey1:   
licenseKey2: 


#PAYG
#licensedBandwidth: 1G | 200m | 25m

#BIG-IQ        
#bigIqLicewnseHost: 
#bigIqLicenseUsername:
#bigIqLicensePassword:
#bigIqLicwensePool:

#Network        
numberOfExternaslIps: 2
#vnetAddressPrefix:

#Cluster        
#enableNetworkFailover:
#internalLoadBalancerType:
#internalLoadBalanceProbePort:

#System                
#ntpServer:
#timeZone:
#restrictedSrvcAddress:
#tagValues:
#allowUasgeAnalytics:
