---

- name: Create Demo VIP, pool and policy
  hosts: f5demo.eastus.cloudapp.azure.com
  connection: local

  tasks:
   - name: Create pool
     bigip_pool:  
       user: "f5admin"
       password: "ChangeMeNow!!!"
       server: f5demo.eastus.cloudapp.azure.com
       validate_certs: "no"
       name: "web_pool"
       monitor_type: "and_list"
       monitors: "http"
     delegate_to: localhost
   
   - name: Add Node 
     bigip_node:  
       user: "f5admin"
       password: "ChangeMeNow!!!"
       server: f5demo.eastus.cloudapp.azure.com
       validate_certs: "no"
       fqdn: "f5-web-app-demo.azurewebsites.net"
       name: "f5-web-app-demo.azurewebsites.net"
     delegate_to: localhost

   - name: Add member to pool
     uri:
       url: "https://f5demo.eastus.cloudapp.azure.com/mgmt/tm/ltm/pool/web_pool/members"
       method: "POST"
       validate_certs: no
       user: "f5admin"
       password: "ChangeMeNow!!!"
       force_basic_auth: yes
       body_format: "json"
       body:
         name: "f5-web-app-demo.azurewebsites.net:80"
     delegate_to: localhost
